name:                haskell-hangman
version:             0.1.0.0
github:              "bradleywboggs/haskell-hangman"
license:             BSD3
author:              "Brad Boggs"
maintainer:          "bradleywboggs@gmail.com"
copyright:           "2023 Bradley Boggs"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bradleywboggs/haskell-hangman#readme>

dependencies:
- base >= 4.7 && < 5
- process
- containers
- microlens

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  haskell-hangman:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-hangman

# tests:
  # haskell-hangman-test:
  #   main:                Spec.hs
  #   source-dirs:         test
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - haskell-hangman
